fos_user:
  db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
  firewall_name: main
  user_class: App\Entity\User

  registration:
    confirmation:
      enabled: true
      from_email:
        address:        registration@bp.com
        sender_name:    Demo Registration
      template:   '@FOSUser/Registration/email.txt.twig'
  resetting:
    email:
      from_email:
        address: resetting@example.com
        sender_name: Demo Resetting
  from_email:
    address: noreply@bp.com
    sender_name: You
