swiftmailer:
  transport: '%mailer_transport%'
#  auth_mode: '%mailer_auth_mode%'
  host:      '%mailer_host%'
#  port:      '%mailer_port%'
  username:  '%mailer_user%'
  password:  '%mailer_password%'
#  encryption: '%mailer_encryption%'
  spool: { type: 'memory' }